import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

def is_smtp_configured():
    """Check if SMTP is properly configured."""
    return bool(os.environ.get('SMTP_EMAIL') and os.environ.get('SMTP_PASSWORD'))

def send_newsletter_email(to_email, subject, body_html, pdf_path=None, audio_path=None):
    """Send newsletter via SMTP email with attachments."""
    
    smtp_host = os.environ.get('SMTP_HOST', 'smtp.gmail.com')
    smtp_port = int(os.environ.get('SMTP_PORT', 587))
    smtp_email = os.environ.get('SMTP_EMAIL')
    smtp_password = os.environ.get('SMTP_PASSWORD')
    
    if not smtp_email or not smtp_password:
        raise ValueError("SMTP credentials not configured. Please set SMTP_EMAIL and SMTP_PASSWORD in your environment variables.")
    
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = smtp_email
    msg['To'] = to_email
    
    text_body = body_html.replace('<br>', '\n').replace('<br/>', '\n')
    text_body = ''.join(c for c in text_body if c.isprintable() or c in '\n\t')
    
    msg.attach(MIMEText(text_body, 'plain'))
    msg.attach(MIMEText(body_html, 'html'))
    
    if pdf_path and os.path.exists(pdf_path):
        with open(pdf_path, 'rb') as f:
            pdf_attachment = MIMEBase('application', 'pdf')
            pdf_attachment.set_payload(f.read())
            encoders.encode_base64(pdf_attachment)
            pdf_attachment.add_header(
                'Content-Disposition',
                f'attachment; filename="{os.path.basename(pdf_path)}"'
            )
            msg.attach(pdf_attachment)
    
    if audio_path and os.path.exists(audio_path):
        with open(audio_path, 'rb') as f:
            audio_attachment = MIMEBase('audio', 'mpeg')
            audio_attachment.set_payload(f.read())
            encoders.encode_base64(audio_attachment)
            audio_attachment.add_header(
                'Content-Disposition',
                f'attachment; filename="{os.path.basename(audio_path)}"'
            )
            msg.attach(audio_attachment)
    
    try:
        server = smtplib.SMTP(smtp_host, smtp_port)
        server.starttls()
        server.login(smtp_email, smtp_password)
        server.sendmail(smtp_email, to_email, msg.as_string())
        server.quit()
        return True
    except Exception as e:
        print(f"Email sending error: {e}")
        raise

def create_newsletter_email_body(newsletter_title, overall_summary, article_count):
    """Create HTML email body for newsletter."""
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .header {{ background: linear-gradient(135deg, #1a73e8, #4285f4); color: white; padding: 30px; text-align: center; }}
            .content {{ padding: 30px; max-width: 600px; margin: 0 auto; }}
            .summary {{ background: #f5f5f5; padding: 20px; border-radius: 10px; margin: 20px 0; }}
            .footer {{ text-align: center; padding: 20px; color: #666; font-size: 12px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>{newsletter_title}</h1>
        </div>
        <div class="content">
            <p>Hello!</p>
            <p>Your personalized newsletter is ready with <strong>{article_count} articles</strong> curated just for you.</p>
            
            <div class="summary">
                <h3>Today's Highlights</h3>
                <p>{overall_summary}</p>
            </div>
            
            <p>We've attached both the PDF and audio versions of your newsletter for your convenience.</p>
            <p>Enjoy your reading!</p>
        </div>
        <div class="footer">
            <p>Generated by Your Personal Newsletter App</p>
        </div>
    </body>
    </html>
    """
    return html
